### ISSUE TITLE
Move trunk to root?

### ISSUE THREAD

**Issue by Sjors** [pseudozach/wp-lightning-comments#1]
Not sure how your subversion to git bridge works, but it would be easier if the main content is in the root folder, not trunk.

This lets users `git clone` the repo right into their `plugins` folder.

**Comment by pseudozach** [comment]
The reason I have it this way is because I do svn ci the root folder to wordpress but sure I guess that's not relevant to others that use this.

My alternative was putting instructions for others to zip the trunk folder and upload to their WordPress plugins folder.

**Comment by Sjors** [comment]
I think the closer you get to a regular (Github) git repo code layout, the more likely you get contributors.
