### ISSUE TITLE
Make payment valid for all posts

### ISSUE THREAD

**Issue by Sjors** [pseudozach/wp-lightning-comments#4]
Right now it seems the payment only allows you to comment on one post. I'd like it to be valid for all posts (this could be a setting).

In terms of the cat and mouse game between spammers and honest users, the current behaviour is overkill :-)

**Comment by pseudozach** [comment]
Fair enough, you may have noticed when a payment is made we set a parameter in localstorage so this should be an easy to implement as a configurable flag.

**Comment by pseudozach** [comment]
this commit should fix this issue: https://github.com/pseudozach/wp-lightning-comments/commit/78d7e228a2f615aa5b0e62a5ef00487ecc34026b

give it a try and let me know if it's ok

**Comment by Sjors** [comment]
Works!

**Comment by Sjors** [comment]
When the cat & mouse game with spammers gets more interesting, you may want to use a less trivial cookie value. The easiest might be to store a hash on the server and a pre-image on the client. The pre-image could be: invoice id + path.

That still allows spammers to copy the preimage between browsers. If that happens we could limit a preimage to e.g. 10 comments.
